@startuml


class Convert {
    +static void ascii(const Image *image,const std::string& outputFilePath);
    +static void grayscale(Image *image);
    +static std::vector<std::vector<Pixel>> resized_image(Image *image, int new_height, int new_width);
   -static float map(float value, float start1, float stop1, float start2, float stop2);


}
@enduml